[tox]
env_list =
    py31{0,1,2,3}
minversion = 4.24.1

[testenv]
runner = uv-venv-lock-runner
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
dependency_groups = test
commands =
    pytest {tty:--color=yes} {posargs}

[testenv:lint]
runner = uv-venv-lock-runner
description = lint check with ruff
dependency_groups = lint
commands =
    ruff check . {posargs}

[testenv:type]
runner = uv-venv-lock-runner
description = type check with mypy
dependency_groups = type
commands =
    mypy src {posargs}
